
extension StringExtension on String {
  String capitalize() {
    if (isEmpty) return this;
    return "${this[0].toUpperCase()}${substring(1)}";
  }

  String acronymFromName() {
    final words = trim().split(RegExp(r'\s+')).where((word) => word.isNotEmpty).toList();
    if (words.isEmpty) {
      return '';
    }

    const stopWords = {
      'a',
      'an',
      'and',
      'as',
      'at',
      'by',
      'for',
      'from',
      'in',
      'of',
      'on',
      'or',
      'the',
      'to',
      'with',
      'about',
      'above',
      'after',
      'again',
      'against',
      'all',
      'am',
      'any',
      'are',
      'arent',
      'be',
      'because',
      'been',
      'before',
      'being',
      'below',
      'between',
      'both',
      'can',
      'cant',
      'did',
      'didnt',
      'do',
      'does',
      'doesnt',
      'doing',
      'dont',
      'down',
      'during',
      'each',
      'etc',
      'few',
      'further',
      'had',
      'hadnt',
      'has',
      'hasnt',
      'have',
      'havent',
      'having',
      'he',
      'hed',
      'hell',
      'hes',
      'her',
      'here',
      'heres',
      'hers',
      'herself',
      'him',
      'himself',
      'his',
      'how',
      'hows',
      'i',
      'id',
      'if',
      'into',
      'is',
      'isnt',
      'it',
      'its',
      'itself',
      'ill',
      'im',
      'ive',
      'just',
      'let',
      'lets',
      'me',
      'more',
      'most',
      'must',
      'my',
      'myself',
      'no',
      'nor',
      'not',
      'now',
      'off',
      'once',
      'only',
      'other',
      'ought',
      'our',
      'ours',
      'ourselves',
      'out',
      'over',
      'own',
      'same',
      'she',
      'shed',
      'shell',
      'shes',
      'should',
      'shouldnt',
      'so',
      'some',
      'such',
      'than',
      'that',
      'thats',
      'their',
      'theirs',
      'them',
      'themselves',
      'then',
      'there',
      'theres',
      'these',
      'they',
      'theyd',
      'theyll',
      'theyre',
      'theyve',
      'this',
      'those',
      'through',
      'too',
      'under',
      'until',
      'up',
      'very',
      'via',
      'vs',
      'was',
      'wasnt',
      'we',
      'wed',
      'well',
      'were',
      'weve',
      'werent',
      'what',
      'whats',
      'when',
      'whens',
      'where',
      'wheres',
      'which',
      'while',
      'who',
      'whos',
      'whom',
      'why',
      'whys',
      'will',
      'within',
      'without',
      'wont',
      'would',
      'wouldnt',
      'you',
      'youd',
      'youll',
      'your',
      'youre',
      'yours',
      'yourself',
      'yourselves',
      'youve',
    };

    final filteredWords = words.where((word) {
      final normalized = word.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '');
      return normalized.isNotEmpty && !stopWords.contains(normalized);
    }).toList();

    final wordsToUse = filteredWords.isNotEmpty ? filteredWords : words;

    return wordsToUse
        .map(_firstAlphanumericCharacter)
        .where((char) => char.isNotEmpty)
        .join()
        .toUpperCase();
  }

  static String _firstAlphanumericCharacter(String value) {
    for (final char in value.split('')) {
      if (RegExp(r'[A-Za-z0-9]').hasMatch(char)) {
        return char;
      }
    }
    return '';
  }
}
